// Mocks para o Cash Plan - formato usado pela tela
export const mockTransactions = [
  {
    id: '1',
    date: '2025-12-01T09:15:00',
    user: 'João',
    description: 'Recebimento venda produto A',
    costCenter: 'Vendas',
    payment: 'Dinheiro',
    credit: 1500.0,
    debit: 0,
    status: 'Concluído',
  },
  {
    id: '2',
    date: '2025-12-02T14:30:00',
    user: 'Maria',
    description: 'Pagamento fornecedor X',
    costCenter: 'Compras',
    payment: 'Boleto',
    credit: 0,
    debit: 500.0,
    status: 'Pendente',
  },
  {
    id: '3',
    date: '2025-12-03T11:05:00',
    user: 'Carlos',
    description: 'Serviço de manutenção',
    costCenter: 'TI',
    payment: 'Transferência',
    credit: 0,
    debit: 250.0,
    status: 'Concluído',
  },
  {
    id: '4',
    date: '2025-12-04T16:45:00',
    user: 'Ana',
    description: 'Recebimento aluguel',
    costCenter: 'Administrativo',
    payment: 'Pix',
    credit: 3000.0,
    debit: 0,
    status: 'Concluído',
  },
  {
    id: '5',
    date: '2025-12-05T10:20:00',
    user: 'Admin',
    description: 'Pagamento assinatura',
    costCenter: 'Financeiro',
    payment: 'Cartão',
    credit: 0,
    debit: 120.5,
    status: 'Pendente',
  },
];

export default mockTransactions;
